# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52f7eb34a58ea5a74c5b3ad76efb51cf8e5e6609680e98e7f6dce0fcf3d263ead6c77a42300ecbecc2a729f8c3386f829a6793823d904bcbbd89941c2ed178ca

test:
  secret_key_base: 2235bb5d616b706798d0b5249dc7f0386113231a148a4e8e798f966e480a03c528c1157ef4b847d5cde9a0abb446677428c1d44d3b9c2f6d92de46e04e21a2e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
